### ISSUE TITLE
Remove tags and reset version 

### ISSUE THREAD

**Issue by fredcy** [elm-community/elm-linear-algebra#3]
Delete the existing tags and reset the version number per https://github.com/elm-community/Manifesto/issues/2#issuecomment-166921271.

**Comment by fredcy** [comment]
Can tags be deleted on a fork and then merged as a PR, or does that have to be done directly on this repo?

**Comment by mgold** [comment]
I think you just have to go ahead and do it. I appreciate that you're using PRs and Issues for visibility, but for this sort of housekeeping, just push to master.

**Comment by fredcy** [comment]
I've bumped/reset the version, removed all existing tags, and created a new 1.0.0 tag as planned.

**Comment by mgold** [comment]
Great! We can move the 1.0.0 tag when the library and examples work with 0.16. Since it hasn't been published, that's not a big deal.
