### ISSUE TITLE
Is someone working on additional features

### ISSUE THREAD

**Issue by eskimoblood** [elm-community/elm-linear-algebra#6]
Are there any plans to add a matrix for 2D vectors or  shear and reflect transformations?

**Comment by nphollon** [comment]
No, there isn't any ongoing development. We are maintaining this package primarily as a dependency for elm-webgl.

If you want to do 2D transformations, you might take a look at [Transform2D](http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Transform2D) in the core library. (I haven't used it myself.)

**Comment by eskimoblood** [comment]
But would you accept pull request to add additional feature?

**Comment by nphollon** [comment]
You are welcome to submit a PR. New features will have to be run by evancz and johnpmayer.

**Comment by mgold** [comment]
(Because of #5)
