### ISSUE TITLE
Incorrect definition of makeFrustrum

### ISSUE THREAD

**Issue by mchav** [elm-community/elm-linear-algebra#8]
I elm the function is defined as:
    makeFrustrum : Float -> Float -> Float -> Float -> Float -> Float -> Float -> Mat4
    makeFrustrum = Native.MJS.m4x4makeFrustrum

In native the `makeFrustrum` takes 6 arguments and an optional matrix `r` to store the return value in. The last argument of type Float causes an error. Additional the word is misspelt in the Elm package (frustrum instead of frustum).

**Comment by nphollon** [comment]
Fixed by #9
